<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="personnel.css"?>
<!DOCTYPE personnel [
  <!ELEMENT personnel (person)+>

  <!ELEMENT person(name,id,role,salary)>
  <!ATTLIST person private ("Yes"|"No") #REQUIRED>

  <!ELEMENT name (#PCDATA)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT role (#PCDATA)>
  <!ELEMENT salary (#PCDATA)>
]/>
<personnel>

   <person private="no">
     <name> Bill Gates </name>
     <id> bg234 </id>
     <role> Tea Boy </role>
     <salary> 7800 </salary>
   </person>

   <person private="no">
     <name> Steve Jobs </name>
     <id> sj20 </id>
     <role> Mail Room Assistant </role>
     <salary> 8200 </salary>
   </person>

   <person private="yes">
     <name> Alan Sugar </name>
     <id> as500 </id>
     <role> Chief Executive </role>
     <salary> 390000 </salary>
   </person>

   <person private="no">
     <name> Clive Sinclair </name>
     <id> c5 </id>
     <role> Mad Inventor </role>
     <salary> 25000 </salary>
   </person>

</personnel>
